# Generated by Django 4.2.7 on 2023-11-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('edad', models.IntegerField()),
                ('materia', models.CharField(choices=[('Programación Lógica', 'Programación Lógica'), ('Álgebra', 'Álgebra'), ('Programación Orientada a Objetos', 'Programación Orientada a Objetos'), ('Administración I', 'Administración I'), ('Contabilidad', 'Contabilidad'), ('Principios de Economía', 'Principios de Economía'), ('Introducción al Derecho', 'Introducción al Derecho'), ('Teoría de la Persona', 'Teoría de la Persona'), ('Derecho Penal I', 'Derecho Penal I')], max_length=128)),
            ],
        ),
    ]
